/*
 * 1Password Connect
 * REST API interface for 1Password Connect.
 *
 * The version of the OpenAPI document: 1.5.7
 * Contact: support@1password.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.APIRequestResourceVault;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for APIRequestResource
 */
public class APIRequestResourceTest {
    private final APIRequestResource model = new APIRequestResource();

    /**
     * Model tests for APIRequestResource
     */
    @Test
    public void testAPIRequestResource() {
        // TODO: test APIRequestResource
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'vault'
     */
    @Test
    public void vaultTest() {
        // TODO: test vault
    }

    /**
     * Test the property 'item'
     */
    @Test
    public void itemTest() {
        // TODO: test item
    }

    /**
     * Test the property 'itemVersion'
     */
    @Test
    public void itemVersionTest() {
        // TODO: test itemVersion
    }

}
