/*
 * 1Password Connect
 * REST API interface for 1Password Connect.
 *
 * The version of the OpenAPI document: 1.5.7
 * Contact: support@1password.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Field;
import com.konfigthis.client.model.FullItemAllOfSections;
import com.konfigthis.client.model.ModelFile;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FullItemAllOf
 */
public class FullItemAllOfTest {
    private final FullItemAllOf model = new FullItemAllOf();

    /**
     * Model tests for FullItemAllOf
     */
    @Test
    public void testFullItemAllOf() {
        // TODO: test FullItemAllOf
    }

    /**
     * Test the property 'sections'
     */
    @Test
    public void sectionsTest() {
        // TODO: test sections
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

    /**
     * Test the property 'files'
     */
    @Test
    public void filesTest() {
        // TODO: test files
    }

}
