/*
 * 1Password Connect
 * REST API interface for 1Password Connect.
 *
 * The version of the OpenAPI document: 1.5.7
 * Contact: support@1password.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.LinkedHashSet;
import java.util.Set;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * The recipe is used in conjunction with the \&quot;generate\&quot; property to set the character set used to generate a new secure value
 */
@ApiModel(description = "The recipe is used in conjunction with the \"generate\" property to set the character set used to generate a new secure value")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class GeneratorRecipe {
  public static final String SERIALIZED_NAME_LENGTH = "length";
  @SerializedName(SERIALIZED_NAME_LENGTH)
  private Integer length = 32;

  /**
   * Gets or Sets characterSets
   */
  @JsonAdapter(CharacterSetsEnum.Adapter.class)
 public enum CharacterSetsEnum {
    LETTERS("LETTERS"),
    
    DIGITS("DIGITS"),
    
    SYMBOLS("SYMBOLS");

    private String value;

    CharacterSetsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CharacterSetsEnum fromValue(String value) {
      for (CharacterSetsEnum b : CharacterSetsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CharacterSetsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CharacterSetsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CharacterSetsEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CharacterSetsEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CHARACTER_SETS = "characterSets";
  @SerializedName(SERIALIZED_NAME_CHARACTER_SETS)
  private Set<CharacterSetsEnum> characterSets = null;

  public static final String SERIALIZED_NAME_EXCLUDE_CHARACTERS = "excludeCharacters";
  @SerializedName(SERIALIZED_NAME_EXCLUDE_CHARACTERS)
  private String excludeCharacters;

  public GeneratorRecipe() {
  }

  public GeneratorRecipe length(Integer length) {
    if (length != null && length < 1) {
      throw new IllegalArgumentException("Invalid value for length. Must be greater than or equal to 1.");
    }
    if (length != null && length > 64) {
      throw new IllegalArgumentException("Invalid value for length. Must be less than or equal to 64.");
    }
    
    
    this.length = length;
    return this;
  }

   /**
   * Length of the generated value
   * minimum: 1
   * maximum: 64
   * @return length
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "32", value = "Length of the generated value")

  public Integer getLength() {
    return length;
  }


  public void setLength(Integer length) {
    if (length != null && length < 1) {
      throw new IllegalArgumentException("Invalid value for length. Must be greater than or equal to 1.");
    }
    if (length != null && length > 64) {
      throw new IllegalArgumentException("Invalid value for length. Must be less than or equal to 64.");
    }
    
    this.length = length;
  }


  public GeneratorRecipe characterSets(Set<CharacterSetsEnum> characterSets) {
    
    
    
    
    this.characterSets = characterSets;
    return this;
  }

  public GeneratorRecipe addCharacterSetsItem(CharacterSetsEnum characterSetsItem) {
    if (this.characterSets == null) {
      this.characterSets = new LinkedHashSet<>();
    }
    this.characterSets.add(characterSetsItem);
    return this;
  }

   /**
   * Get characterSets
   * @return characterSets
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Set<CharacterSetsEnum> getCharacterSets() {
    return characterSets;
  }


  public void setCharacterSets(Set<CharacterSetsEnum> characterSets) {
    
    
    
    this.characterSets = characterSets;
  }


  public GeneratorRecipe excludeCharacters(String excludeCharacters) {
    
    
    
    
    this.excludeCharacters = excludeCharacters;
    return this;
  }

   /**
   * List of all characters that should be excluded from generated passwords.
   * @return excludeCharacters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "abc1", value = "List of all characters that should be excluded from generated passwords.")

  public String getExcludeCharacters() {
    return excludeCharacters;
  }


  public void setExcludeCharacters(String excludeCharacters) {
    
    
    
    this.excludeCharacters = excludeCharacters;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GeneratorRecipe instance itself
   */
  public GeneratorRecipe putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeneratorRecipe generatorRecipe = (GeneratorRecipe) o;
    return Objects.equals(this.length, generatorRecipe.length) &&
        Objects.equals(this.characterSets, generatorRecipe.characterSets) &&
        Objects.equals(this.excludeCharacters, generatorRecipe.excludeCharacters)&&
        Objects.equals(this.additionalProperties, generatorRecipe.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(length, characterSets, excludeCharacters, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeneratorRecipe {\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    characterSets: ").append(toIndentedString(characterSets)).append("\n");
    sb.append("    excludeCharacters: ").append(toIndentedString(excludeCharacters)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("length");
    openapiFields.add("characterSets");
    openapiFields.add("excludeCharacters");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GeneratorRecipe
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!GeneratorRecipe.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GeneratorRecipe is not found in the empty JSON string", GeneratorRecipe.openapiRequiredFields.toString()));
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("characterSets") != null && !jsonObj.get("characterSets").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `characterSets` to be an array in the JSON string but got `%s`", jsonObj.get("characterSets").toString()));
      }
      if ((jsonObj.get("excludeCharacters") != null && !jsonObj.get("excludeCharacters").isJsonNull()) && !jsonObj.get("excludeCharacters").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `excludeCharacters` to be a primitive type in the JSON string but got `%s`", jsonObj.get("excludeCharacters").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GeneratorRecipe.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GeneratorRecipe' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GeneratorRecipe> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GeneratorRecipe.class));

       return (TypeAdapter<T>) new TypeAdapter<GeneratorRecipe>() {
           @Override
           public void write(JsonWriter out, GeneratorRecipe value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GeneratorRecipe read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             GeneratorRecipe instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GeneratorRecipe given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GeneratorRecipe
  * @throws IOException if the JSON string is invalid with respect to GeneratorRecipe
  */
  public static GeneratorRecipe fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GeneratorRecipe.class);
  }

 /**
  * Convert an instance of GeneratorRecipe to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

