/*
 * 1Password Connect
 * REST API interface for 1Password Connect.
 *
 * The version of the OpenAPI document: 1.5.7
 * Contact: support@1password.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.APIRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ActivityApi
 */
@Disabled
public class ActivityApiTest {

    private static ActivityApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ActivityApi(apiClient);
    }

    /**
     * Retrieve a list of API Requests that have been made.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getApiRequestsTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        List<APIRequest> response = api.getApiRequests()
                .limit(limit)
                .offset(offset)
                .execute();
        // TODO: test validations
    }

}
