/*
 * 1Password Connect
 * REST API interface for 1Password Connect.
 *
 * The version of the OpenAPI document: 1.5.7
 * Contact: support@1password.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import java.io.File;
import com.konfigthis.client.model.ModelFile;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FilesApi
 */
@Disabled
public class FilesApiTest {

    private static FilesApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new FilesApi(apiClient);
    }

    /**
     * Get all the files inside an Item
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllFilesInsideItemTest() throws ApiException {
        UUID vaultUuid = null;
        UUID itemUuid = null;
        Boolean inlineFiles = null;
        List<ModelFile> response = api.getAllFilesInsideItem(vaultUuid, itemUuid)
                .inlineFiles(inlineFiles)
                .execute();
        // TODO: test validations
    }

    /**
     * Get the content of a File
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getContentTest() throws ApiException {
        UUID vaultUuid = null;
        UUID itemUuid = null;
        String fileUuid = null;
        File response = api.getContent(vaultUuid, itemUuid, fileUuid)
                .execute();
        // TODO: test validations
    }

    /**
     * Get the details of a File
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFileDetailsTest() throws ApiException {
        UUID vaultUuid = null;
        UUID itemUuid = null;
        UUID fileUuid = null;
        Boolean inlineFiles = null;
        ModelFile response = api.getFileDetails(vaultUuid, itemUuid, fileUuid)
                .inlineFiles(inlineFiles)
                .execute();
        // TODO: test validations
    }

}
