/*
 * 1Password Connect
 * REST API interface for 1Password Connect.
 *
 * The version of the OpenAPI document: 1.5.7
 * Contact: support@1password.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.HealthServerStateCheckResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HealthApi
 */
@Disabled
public class HealthApiTest {

    private static HealthApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new HealthApi(apiClient);
    }

    /**
     * Ping the server for liveness
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkLivenessTest() throws ApiException {
        String response = api.checkLiveness()
                .execute();
        // TODO: test validations
    }

    /**
     * Get state of the server and its dependencies.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void serverStateCheckTest() throws ApiException {
        HealthServerStateCheckResponse response = api.serverStateCheck()
                .execute();
        // TODO: test validations
    }

}
